#!/bin/bash
basedir="$( cd "$(dirname "$BASH_SOURCE")" ; pwd -P )"
sdhashdir="$basedir/sdhash"
mrshv2dir="$basedir/mrshv2"
ssdeepdir="$basedir/ssdeep"

cd $sdhashdir
make
cd $mrshv2dir
make
cd $ssdeepdir
./bootstrap
./configure
make
sudo mkdir -p /usr/local/lib/bulk_extractor
sudo cp $ssdeepdir/.libs/libfuzzy.so* /usr/local/lib/bulk_extractor

cd $basedir
if [[ $BE_ABS_PATH ]]
	then
		make BE_ABS_PATH=$BE_ABS_PATH
	else
		make
	fi
sudo make install
